backend:
  name: git-gateway

media_folder: public/img
public_folder: img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: Facebook Meta Data, name: facebook, widget: object,
            fields: [
              {
                label: Title,
                name: ogTitle,
                widget: string,
              },
              {
                label: Image (url of image),
                name: ogImage,
                widget: string,
              }
            ]}
          - {label: Twitter Meta Data, name: twitter, widget: object,
            fields: [
              {
                label: Card,
                name: card,
                widget: string,
              },
              {
                label: Description,
                name: description,
                widget: string,
              },
              {
                label: Title,
                name: title,
                widget: string,
              },
              {
                label: Image (url of image),
                name: image,
                widget: string
              }
            ]}
          - {
            label: Header,
            name: header,
            widget: object,
            fields: [
              {label: Image, name: image, widget: image},
              {label: VanHacks Logo, name: vanhacksLogo, widget: image },
              {label: Date, name: date, widget: string},
              {label: Button Title, name: buttonTitle, widget: string,},
              {label: Button URL Link, name: buttonURL, widget: string,}
            ]
          }
          - {label: Hacking and Caring with, name: collaborators, widget: list, 
            fields: [
                  {
                    label: Organization Logo,
                    name: image,
                    widget: image,
                  },
                  {
                    label: Alt,
                    name: alt,
                    widget: string,
                  },
                  {
                    label: URL,
                    name: href,
                    widget: string,
                  }
                ]
              }
          - {
            label: About,
            name: about,
            widget: object,
            fields: [
              {
                label: Title,
                name: title,
                widget: string,
              },
              {
                label: 'Description',
                name: descriptionMarkdown,
                widget: 'markdown'
              },
              {
                label: Image,
                name: image,
                widget: image,
              }
            ]
          }

          - {
          label: Groups,
          name: groups,
          widget: object,
          fields: [
            {
              label: Title,
              name: title,
              widget: string,
            },
            {
                label: 'Description',
                name: descriptionMarkdown,
                widget: 'markdown'
            },
            {
              label: Button Title,
              name: buttonTitle,
              widget: string,
            },
            {
              label: Button URL,
              name: buttonUrl,
              widget: string,
            },
            {
              label: Instructions,
              name: instructions,
              widget: list,
              fields: [
                {
                  lable: Step,
                  name: step,
                  widget: text,
                }
              ]
            }
          ]
        }

          - {
            label: 'Schedule',
            name: schedule,
            widget: object,
            fields: [
              {
                label: Title,
                name: title,
                widget: string,
              },
              {
                label: Days,
                name: days,
                widget: list,
                fields: [
                  {
                    label: Day,
                    name: day,
                    widget: string,
                  },
                  {
                    label: Time Blocks,
                    name: timeBlocks,
                    widget: list,
                    fields: [
                      {
                        label: Time,
                        name: time,
                        widget: string,
                      },
                      {
                        label: Title,
                        name: title,
                        widget: string,
                      },
                      {
                        label: Location Title,
                        name: locationTitle,
                        widget: string,
                        required: false
                      },
                      {
                        label: Location Url,
                        name: locationUrl,
                        widget: string,
                        required: false
                      },
                      {
                        label: Description,
                        name: description,
                        widget: text,
                      }
                    ]
                  }
                ]
              }
            ]
        }
          - {
            label: Sponsors,
            name: sponsors,
            widget: object,
            fields: [
              {
                label: Title,
                name: title,
                widget: string,
              },
              {
                label: Description,
                name: description,
                widget: string,
              },
              {
                label: Button Title,
                name: buttonTitle,
                widget: string,
              },
              {
                label: Button URL (file name in public folder),
                name: buttonUrl,
                widget: string,
              },
              {
                label: Founding Sponsors,
                name: foundingSponsors,
                widget: list,
                fields: [
                  {
                    label: Sponsor Image,
                    name: sponsor,
                    widget: image,
                  },
                  {
                    label: Alt,
                    name: alt,
                    widget: string
                  },
                  {
                    label: Url,
                    name: url,
                    widget: string,
                  },
                  {
                    label: Description,
                    name: description,
                    widget: text,
                  }
                ]
              },
              {
                label: Event Sponsors Title,
                name: eventSponsorsTitle,
                widget: string
              },
              {
                label: Event Sponsors,
                name: eventSponsors,
                widget: list,
                fields: [
                  {
                    label: Sponsor Image,
                    name: sponsor,
                    widget: image,
                  },
                  {
                    label: Alt,
                    name: alt,
                    widget: string,
                  },
                  {
                    label: Url,
                    name: url,
                    widget: string,
                  },
                  {
                    label: Tier,
                    name: tier,
                    widget: number,
                  }
                ]
              }
            ]
          }

          - {
            label: Judges,
            name: judges,
            widget: list,
            fields: [
              {
                label: Judge Image,
                name: judge,
                widget: image,
              },
              {
                label: Full Name,
                name: fullName,
                widget: string,
              },
              {
                label: Job Title,
                name: jobTitle,
                widget: string,
              },
              {
                label: Description,
                name: description,
                widget: text,
              }
            ]
          }

          - {
            label: Hosts,
            name: hosts,
            widget: list,
            fields: [
              {
                label: Host Image,
                name: host,
                widget: image,
              },
              {
                label: Full Name,
                name: fullName,
                widget: string,
              },
              {
                label: Description,
                name: description,
                widget: string,
              },
              {
                label: Social Media Url,
                name: socialMediaUrl,
                widget: string,
              }
            ]
          }

          - {
            label: Info,
            name: info,
            widget: object,
            fields: [
              {
                label: Title,
                name: title,
                widget: string,
              },
              {
                label: 'Rules - Old , Saving for 2021',
                name: rules,
                widget: list,
                fields: [
                  {
                    label: First Rule In Row,
                    name: firstRule,
                    widget: string,
                  },
                  {
                    label: Description,
                    name: firstDescription,
                    widget: text,
                  },
                  {
                    label: Second Rule In Row,
                    name: secondRule,
                    widget: string,
                    required: false
                  },
                  {
                    labe: Second Description In Row,
                    name: secondDescription,
                    widget: text,
                    required: false
                  }
                ]
              },
              {
                label: Rules - Lite,
                name: rulesLite,
                widget: list,
                fields: [
                  {
                    label: Rule,
                    name: rule,
                    widget: string,
                  },
                  {
                    label: Description,
                    name: description,
                    widget: markdown,
                  },
                ]
              },
              {
                label: 'FAQs - Old, Saving for 2021',
                name: faq,
                widget: list,
                fields: [
                  {
                    label: First Question In Row,
                    name: firstQ,
                    widget: string,
                  },
                  {
                    label: Answer Part 1,
                    name: firstAnswerOne,
                    widget: text,
                  },
                  {
                    label: Hyper Link Text,
                    name: firstHrefText,
                    widget: string,
                    required: false
                  },
                  {
                    label: Hyper Link URL,
                    name: firstHrefUrl,
                    widget: string,
                    required: false
                  },
                  {
                    label: Answer Part 2,
                    name: firstAnswerTwo,
                    widget: text,
                    required: false
                  },
                  {
                    label: Second Question In Row,
                    name: secondQ,
                    widget: string,
                    required: false
                  },
                  {
                    label: Answer Part 1,
                    name: secondAnswerOne,
                    widget: text,
                    required: false
                  },
                  {
                    label: Hyper Link Text,
                    name: secondHrefText,
                    widget: string,
                    required: false
                  },
                  {
                    label: Hyper Link URL,
                    name: secondHrefUrl,
                    widget: string,
                    required: false
                  },
                  {
                    label: Answer Part 2,
                    name: secondAnswerTwo,
                    widget: text,
                    required: false
                  }
                ]
              },
              {
                label: FAQs - Lite,
                name: faqLite,
                widget: list,
                fields: [
                  {
                    label: Question,
                    name: question,
                    widget: string,
                  },
                  {
                    label: Answer,
                    name: answer,
                    widget: markdown,
                  }
                ]
              }
            ]
          }